# Generated by Django 3.0.8 on 2020-08-15 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='duration',
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
