# Generated by Django 3.0.8 on 2020-08-28 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200817_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watch_list',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
